export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_DISHES = 'ADD_DISHES';
export const DISHES_LOADING = 'DISHES_LOADING';
export const DISHES_FAILED = 'DISHES_FAILED';
export const ADD_PROMOTION = 'ADD_PROMOTION';
export const PROMOTION_LOADING = 'PROMOTION_LOADING';
export const PROMOTION_FAILED = 'PROMOTION_FAILED';